# Generated by Django 5.2.6 on 2025-09-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.TextField(blank=True),
        ),
    ]
